language: java
jdk:
- oraclejdk7
branches:
  except:
  - /^(?i:wip).*$/
sudo: false
after_success:
- .config/deploy-artifacts.sh
- .config/publish-javadocs.sh
- mvn clean cobertura:cobertura coveralls:report