language: java

jdk:
  - oraclejdk7
  - openjdk6
  
branches:
  only:
    - master
    - development

after_success:
    - mvn javadoc:aggregate
    - mvn site:site
    - chmod +x .config/deploy-site.sh
    - .config/deploy-javadoc.sh
    - chmod +x .config/deploy-artifacts.sh
    - .config/deploy-artifacts.sh